# Site settings
title: The Data Hide
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Data Hide is a series of monthly meetings organised by the Open Data Science Initiative.
baseurl: "/datahide/" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  sods
comments: true
disqus: opendsicc

analytics:
  google:
    tracking_id: UA-62964644-1

# Build settings
markdown: kramdown
